### PR TITLE
chore: Bring master in-line with upstream

### PR DESCRIPTION
**Pull request by danmrichards**
Brings the master branch in-line with latest changes from the upstream repository

### CODE REVIEW

**Comment by danmrichards** [comment]
@lwaddicor Feel free to ignore this; just opening it up as I've had to build a branch with the upstream changes to resolve a dependency issue I'm having.

For context, while in the process of updating the version of https://github.com/opencontainers/runc on https://github.com/multiplay/multiplay-go I ran into a dependency issue caused by this fork being out of sync with changes in the upstream

**Comment by lwaddicor** [comment]
Out of interest I wonder if this fork is needed anymore, I got the windows preshutdown hook stuff upstreamed a while ago. Not sure what else (if anything) is different now

**Comment by danmrichards** [comment]
Good to know, didn't look like anything else was different tbh

**Comment by stevenh** [comment]
I think @lwaddicor is correct. The only other changes we had here we're additional sysctl support which I upstreamed ages ago, so we should indeed be able to remove this now.

**Comment by danmrichards** [comment]
Nice, yeah confirmed the pre-shutdown stuff is there upstream - https://github.com/multiplay/golang-sys/commit/b6458a4ca117e97c19a5fd843400b3b8874db9bd

Shall close, thanks both.

@lwaddicor When time allows, we should find a moment to update multiplay-go to point back at the upstream instead of this fork

**Pull request closed without merging**
